version: "3.9"

services:
  learninglocker:
    ports:
      - 3030:3000
    env_file:
      - .env.docker
    volumes:
      - .env.docker:/app/.env:ro

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
