version: "3.9"

volumes:
  logs:
  storage:
  mongodb:

services:
  learninglocker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000
    volumes:
      - logs:/app/logs
      - storage:/app/storage

  mongodb:
    image: "mongo:4.2"
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb:/data/db

  redis:
    image: "redis:5-alpine"
